# permissions for end users to edit controllerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllerconfig-editor-role
rules:
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - controllerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - controllerconfigs/status
  verbs:
  - get
