# permissions for end users to edit devicedrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicedriver-editor-role
rules:
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - devicedrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - devicedrivers/status
  verbs:
  - get
