# permissions for end users to edit networknodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networknode-editor-role
rules:
- apiGroups:
  - driver.ndd.henderiw.be
  resources:
  - networknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - driver.ndd.henderiw.be
  resources:
  - networknodes/status
  verbs:
  - get
