
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - devicedrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - networknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - networknodes/finalizers
  verbs:
  - update
- apiGroups:
  - dvr.ndd.henderiw.be
  resources:
  - networknodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - locks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providerrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providerrevisions/finalizers
  verbs:
  - update
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providerrevisions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - pkg.ndd.henderiw.be
  resources:
  - providers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  - create
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - bind
  - create
  - escalate
  - get
  - list
  - patch
  - update
  - watch
